### ISSUE TITLE
Decide on the platforms we want to cover

### ISSUE THREAD

**Issue by kdex** [shiromino/shiromino#10]
We currently support OpenGL for an improved feature set, but we haven't decided on the set of platforms we'd like to cover with this repository. There's a [PS Vita port](https://www.youtube.com/watch?v=KAwkiZJ4b-U) of the game somewhere (which doesn't look GPU-accelerated), and there are also plans to port the game to the Nintendo 3DS.

### Availability matrix

| Platform                 | Metal | OpenGL  | Vulkan |
| -------------------------|---------|--------------|----------|
| Linux                      | No     | Yes          | Yes    |
| macOS                  | Yes    | Yes¹         | Yes²   |
| Windows                | No     | Yes          | Yes    |
| PlayStation Vita     | No     | No           | No      |
| Nintendo 3DS        | No     | No           | No      |

¹ via MoltenGL

² via MoltenVK

It currently doesn't look like we're going to support the PlayStation Vita or the Nintendo 3DS in this repository, but more like this work has to happen in forks that would port GPU-related code to their specific target platform.

#### The PlayStation Vita situation

The only way in the homebrew scene to employ the PlayStation Vita's GPU currently is to use [gxmfun](https://github.com/xerpi/gxmfun), which is its own little GPU API. There's also [software implementations](https://bellard.org/TinyGL/) of OpenGL, but they're probably not worth pursuing for us, given that we should strive for at least 60 fps (see video linked above, which is pretty laggy).

#### The Nintendo 3DS situation

The Nintendo 3DS actually has a GPU-accelerated OpenGL library via [Caelina](https://github.com/machinamentum/Caelina) or [ctrgl](https://github.com/minexew/ctrgl). The problem with those is that they're unmaintained, very incomplete, and only cover a subset of OpenGL 1.x, which puts very hard limits on all the other platforms if we were to set that as the lowest common denominator.

Currently, it looks like we could achieve the most with the lowest effort by replacing OpenGL with Vulkan and by letting forks cover less dominant platforms.

/cc @nightmareci

**Comment by nightmareci** [comment]
There's a port of SDL2 for PlayStation Vita
<https://github.com/rsn8887/SDL-Vita>, that as of writing this message is
at version 2.0.8. Since there are (incomplete) ports of OpenGL for 3DS, I
would assume a full port of SDL2 to 3DS is possible (ideally using native
3DS APIs rather than OpenGL), and there is an old, abandoned 3DS port of
SDL2 <https://github.com/xerpi/SDL-3DS>, but that might not even be
complete enough to use. We could integrate support for Vita, but I think
that'd only make sense once full theming is possible, when Shiromino isn't
hard-coded for one theme only in a 640x480 viewport, so we could have a
custom theme that perfectly matches the Vita's screen, as the existing Vita
port by Tearff <https://github.com/Tearff/shiromino> had to have the
hard-coded graphics code changed to use the whole screen on Vita.

I would like the game to be made in a way that the backend can be changed
out though, so non-SDL2 ports are possible; that would allow enhanced ports
that still work with the base 2D theme used by the SDL2 ports, like adding
stereographic 3D to the 3DS port, perhaps just making the non-background
graphics on a layer visibly closer to the viewer vs. the background being
farther behind that layer.

Also, MoltenGL is a commercial product, so it's not so well suited for our
open source, freely available game. But MoltenVK is available in an open
source, free version, so we could use that.

**Comment by kdex** [comment]
@nightmareci: Thanks for providing a link to the PlayStation Vita port; I was unaware that its source code was even out there. Judging from the commits, it seems like the port is actually pretty manageable.

> I would like the game to be made in a way that the backend can be changed out though, so non-SDL2 ports are possible

Yup, I wholeheartedly agree. Also see #25, where the work on `libshiromino` is already being tracked.

> Also, MoltenGL is a commercial product, so it's not so well suited for our open source, freely available game. But MoltenVK is available in an open source, free version, so we could use that.

Sure, that works for me.

That being said, I think we both agree that a Vulkan-based front end is the way forward for this repository, and forks should cover platform-specific, proprietary APIs — be it a DirectX version or the PlayStation Vita's GXM API. Hence, I will close this issue in favor of #28. Feel free to re-open in case I missed something.

**Comment by kdex** [comment]
Also, just for the sake of completeness, I'm linking #21 here, where we track the work for a theme mechanism, which should be relevant for console-specific ports.
