### ISSUE TITLE
Make it possible to delete games from db

### ISSUE THREAD

**Issue by gregorulm** [shiromino/shiromino#41]
It's currently not possible to delete any saved replays.

**Comment by kdex** [comment]
@gregorulm Note that we'll likely overhaul the replay system anyway, see #13. I have yet to see a real use case for the SQLite database, so I think we're just going to phase it out in favor of the file system (i. e. one file per replay).

If you think that your issue is already covered by #13, you can close this one.

**Comment by gregorulm** [comment]
Apart from the fact that this change would make #38, which would be a rather neat addition to Shiromino, more difficult to achieve, I see some potential problems with this intended change. First, there is a lot of overhead due to the minimum block sizes for small files. This differs depending on the chosen file system, but it would add up quickly. Second, how would you easily navigate a folder with thousands of small files (from Shiromino, I mean)? This is way faster in a database, which you could easily filter or even write complex custom queries for. Third, you can't easily optimize storage of a large number of smaller files, whereas this comes for free with `sqlite` as the database is just one file.

On a side note, you may be surprised how quickly you accumulate many thousands of short replays. Most of those are probably redundant, but sometimes even a G2 Death 500 practice session that barely lasted 15 seconds can have the occasioal interesting moves in it, so it's nice to have the chance to replay it. Saving every game by default is, IMO, the right decision. Yet, this would not work so well if each replay was saves as its own file.

**Comment by kdex** [comment]
Yup, those are all very valid points. I'm guessing that the file synchronization problem described in #13 is probably a non-issue, since on a local network, clients are either always connected and thus synchronizing anyway, or in case of mobile devices, it's rare to take more than one device with you that you play on before you return to your home network.

I'm convinced, let's keep the SQLite database and just make it more convenient to use. Thanks for your input!

**Comment by gregorulm** [comment]
You're welcome.

**Comment by FelicityVi** [comment]
Since the 0.2.0 update, replays can now be deleted from within Shiromino by pressing and holding the **shift key** and clicking on the button at the top of the screen that says "Delete." I'll also make this clearer on the replay screen in the next update.

**Comment by gregorulm** [comment]
@FelicityVi This is a good addition, but it would be great to have the ability to delete records in bulk. In the current setup, clearing hundreds of pages of replays, which is easy to accumulate if you practice G2 Death/G3 Terror, would be very time consuming as you have to click the "delete" button once per replay.
