### ISSUE TITLE
Don't render mouse pointer

### ISSUE THREAD

**Issue by gregorulm** [shiromino/shiromino#51]
In macOS (maybe also in the Windows build), the game renders a mouse pointer, which is superfluous and distracting as you have to move it out of the way in order to not distract you. I'd suggest not rendering a mouse pointer at all as it is not needed. In fact, not needing to use a mouse to navigate the menu is one of the reasons Shiromino has such a great UX.

**Comment by kdex** [comment]
> In fact, not needing to use a mouse to navigate the menu is one of the reasons Shiromino has such a great UX.

Totally agree with that.

However, I'm sure that just not rendering the cursor would break a few software accessibility guidelines. In its current form, the game doesn't need it, and especially in-game, it becomes a nuisance.

I would love for revamped menus (#6) to be mouse-accessible as well, so if anything, we should much rather conditionally hide it based on whether you're currently in a menu or not, and based on whether there have been any recent mouse events (so that you don't get to see it when you're just using a controller or the keyboard).

**Comment by gregorulm** [comment]
I'd be careful with adding mouse support. If it's additional, then there would not be much of an issue, apart from the extra work for you, but if you force it on people, you'd negatively affect UX for your hardcore user base. I'd find it quite alienating, to be honest, if I had to click around with the mouse before starting a game and in between games.

**Comment by kdex** [comment]
Yup, no worries. Mouse support will be entirely additional, and at no point should there be an instance in the game where you would have to use a mouse or even see a cursor when you don't even use the mouse. (Same goes for all other input methods; i.e., you shouldn't have to use a controller if you don't want to, neither should you have to use the keyboard if you don't want to.)

**Comment by nightmareci** [comment]
As a compromise of not completely hiding the mouse altogether, and still hiding it when you don't want it, I suggest the following:

- On startup, the mouse is hidden, until a mouse motion or mouse button press is received. (This makes use on a dedicated setup nicer, like with an arcade cabinet, where you never want to bother with the mouse at all, and doesn't require any special setting to disable the mouse)
- If any game input is received (joystick or keyboard inputs for directions, A/B/C/D, etc.), the mouse will be hidden, and remain hidden until a mouse input is received. This applies unconditionally and globally, not just in specific parts of the program.

That type of mouse handling would also ensure good accessibility, so you wouldn't be confused as to where the mouse is if it happens to be moving over the window.

I also agree that the game should always be fully accessible with game controls, with mouse use always being optional.

**Comment by kdex** [comment]
@nightmareci Sounds perfect. The only thing I'd like to ask would be for you to clarify what you meant when you said "game input":

> If any game input is received (joystick or keyboard inputs for directions, A/B/C/D, etc.),

 I'm sure you must mean any physical non-mouse input? At first, I thought that "game input" refers to our *logical* game input (i. e. `struct`s with `bool`s, since they map to our logical `A`, `B`, `C`, `D`, and so on), but hiding the cursor only really makes sense one layer of abstraction before that, when the context also includes the *physical* device that emitted the signal.

If that's what you meant though, I'm completely with you on this.

**Comment by nightmareci** [comment]
Yeah, I meant that the mouse should be hidden only when logical inputs are received, not any joystick/keyboard input whether mapped to logical inputs or not, since we can assume if you press a mapped, logical input, you're intending to not use the mouse.
