### ISSUE TITLE
Difficulty 100 is not a uniform distribution

### ISSUE THREAD

**Issue by 2Tie** [shiromino/shiromino#66]
In random.h and random.cc, comments declare the intention for difficulty 100.0 to be uniform piece distribution: 
https://github.com/shiromino/shiromino/blob/dc57453367aaa0789291d21c90d629bbd27f60bf/src/random.h#L111
https://github.com/shiromino/shiromino/blob/dc57453367aaa0789291d21c90d629bbd27f60bf/src/random.cc#L720

however, in random.cc, the weight scaling was changed to occur starting at difficulty 30.0, but doesn't scale fully; at difficulty 100, piece weights are only adjusted 70% of the way to a uniform distribution. A fix would be to change the 100.0 to 70.0 (or 100.0 - 30.0 for clarity?) in the following line:
https://github.com/shiromino/shiromino/blob/dc57453367aaa0789291d21c90d629bbd27f60bf/src/random.cc#L722

alternatively, if this is now the intended behaviour, then i have linked the comments to change that contradict this.
might be venturing into unrelated enhancement/refactor territory here, but i feel turning the numerous 30.0 values into a constant would be a good idea as well?

**Comment by kdex** [comment]
We're going to have to assume that the comments were supposed to document the intended behavior, so I agree with you.

I went ahead and fixed it in dfd95be. (I also removed a little bit of comment clutter.)

Thanks for reporting this!

**Comment by kdex** [comment]
@2Tie After discussion this with Felicity, it turns out that the comment was outdated; uniformly distributing the pieces is not what the game is supposed to do.

I've replaced dfd95be with 4aafc7fa3384ef2283a98e36b7360c1de1ec1218.

Thank you!

**Comment by FelicityVi** [comment]
@2Tie Adding the "threshold" of 30.0 was a change I made years ago, and it's more like an offset to the numbers than anything. Before that change, 0.0 difficulty (equivalent to 30.0 now) was quite hard, which didn't make sense to me, as you would expect a difficulty of 0.0 to make the game pretty easy. The randomizer felt nicely balanced other than this, so I simply offset the numbers instead of using negative difficulty numbers throughout the Pentomino C mode.

As an aside, negative difficulty numbers and numbers above 130.0 function perfectly fine. The lower the value, the more skewed the randomizer is toward "nicer" pieces. The higher the value, the more skewed it is toward the more brutal pentominoes. At the extremes of negative and positive infinity, it would be 100% T tetrominoes and 100% X pentominoes, respectively, because I have marked those as the best and worst pieces, respectively.

Just writing this here to fully settle the record on this oddity. Behavior should remain as-is.
